version: '3.8'

services:
  api:
    build: .
    command: python api.py
    # УБИРАЕМ ports: "8000:8000". 
    # Теперь API доступен только ДРУГИМ контейнерам по внутренней сети
    volumes:
      - .:/app
    restart: unless-stopped
    env_file: .env

  bot:
    build: .
    command: python main.py
    depends_on:
      - api
    volumes:
      - .:/app
    restart: unless-stopped
    env_file: .env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      # ФРОНТЕНД берет на себя роль единственной открытой "двери"
      - "127.0.0.1:8000:80" 
    depends_on:
      - api
    restart: unless-stopped
